In [2]:
# imports
import pandas as pd
import datetime

In [3]:
# read in csv file to dataframe
original_df = pd.read_csv('Speed_Camera_Violations1.csv')
original_df

,STREET,ADDRESS,CAMERA ID,VIOLATION DATE,VIOLATIONS,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION
0,N HUMBOLDT,1111 N HUMBOLDT,CHI010,4/10/2015,67,NaN,NaN,NaN,NaN,NaN
1,N HUMBOLDT,1111 N HUMBOLDT,CHI010,4/25/2015,71,NaN,NaN,NaN,NaN,NaN
2,N HUMBOLDT,1111 N HUMBOLDT,CHI010,4/14/2015,38,NaN,NaN,NaN,NaN,NaN
3,N HUMBOLDT,1111 N HUMBOLDT,CHI010,4/16/2015,55,NaN,NaN,NaN,NaN,NaN
4,N HUMBOLDT,1111 N HUMBOLDT,CHI010,4/24/2015,54,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
308277,W FOREST PRESERVE AV,8020 W FOREST PRESERVE AV,CHI174,6/4/2022,212,1121895.053,1922705.872,41.944319,-87.827378,"(41.944318833069445, -87.8273782786742)"
308278,N NARRAGANSETT AVE,3116 N NARRAGANSETT AVE,CHI132,6/3/2022,5,1133159.075,1920109.559,41.937004,-87.786037,"(41.93700435024341, -87.78603672187927)"
308279,W BELMONT AVE,3810 W BELMONT AVE,CHI089,6/2/2022,11,1150363.864,1921047.101,41.939258,-87.722781,"(41.93925823071868, -87.72278142793657)"
308280,N COLUMBUS DR,450 N COLUMBUS DR,CHI125,6/4/2022,15,1178351.216,1903356.802,41.890122,-87.620461,"(41.890122352505166, -87.62046139513696)"
308281,W ADDISON ST,8006 W ADDISON ST,CHI176,6/4/2022,28,1122009.360,1923001.912,41.945129,-87.826952,"(41.945129353961654, -87.8269516993975)"

In [4]:
# drop null values
df = original_df.dropna()
df

,STREET,ADDRESS,CAMERA ID,VIOLATION DATE,VIOLATIONS,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION
366,W AUGUSTA,3100 W AUGUSTA,CHI011,12/1/2020,23,1155438.363,1906531.351,41.899325,-87.704522,"(41.89932514072566, -87.70452234551168)"
368,W 71ST,3450 W 71ST,CHI015,12/1/2020,19,1154377.984,1857351.591,41.764391,-87.709728,"(41.76439095689881, -87.70972841983624)"
369,W ROOSEVELT,2917 W ROOSEVELT,CHI019,7/28/2020,36,1156991.618,1894531.138,41.866364,-87.699143,"(41.866364024167034, -87.69914296647906)"
370,E 95TH ST,3542 E 95TH ST,CHI141,7/28/2020,8,1201629.280,1842674.179,41.723045,-87.537041,"(41.72304461975978, -87.5370407583455)"
371,S ASHLAND AVE,8345 S ASHLAND AVE,CHI168,7/27/2019,27,1167170.494,1849194.117,41.741742,-87.663073,"(41.741741651401504, -87.66307332925098)"
...,...,...,...,...,...,...,...,...,...,...
308277,W FOREST PRESERVE AV,8020 W FOREST PRESERVE AV,CHI174,6/4/2022,212,1121895.053,1922705.872,41.944319,-87.827378,"(41.944318833069445, -87.8273782786742)"
308278,N NARRAGANSETT AVE,3116 N NARRAGANSETT AVE,CHI132,6/3/2022,5,1133159.075,1920109.559,41.937004,-87.786037,"(41.93700435024341, -87.78603672187927)"
308279,W BELMONT AVE,3810 W BELMONT AVE,CHI089,6/2/2022,11,1150363.864,1921047.101,41.939258,-87.722781,"(41.93925823071868, -87.72278142793657)"
308280,N COLUMBUS DR,450 N COLUMBUS DR,CHI125,6/4/2022,15,1178351.216,1903356.802,41.890122,-87.620461,"(41.890122352505166, -87.62046139513696)"
308281,W ADDISON ST,8006 W ADDISON ST,CHI176,6/4/2022,28,1122009.360,1923001.912,41.945129,-87.826952,"(41.945129353961654, -87.8269516993975)"

In [5]:
# convert date column to datetime
df['VIOLATION DATE'] =pd.to_datetime(df['VIOLATION DATE'])
df

<ipython-input-5-af2cc618d25e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['VIOLATION DATE'] =pd.to_datetime(df['VIOLATION DATE'])

,STREET,ADDRESS,CAMERA ID,VIOLATION DATE,VIOLATIONS,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION
366,W AUGUSTA,3100 W AUGUSTA,CHI011,2020-12-01,23,1155438.363,1906531.351,41.899325,-87.704522,"(41.89932514072566, -87.70452234551168)"
368,W 71ST,3450 W 71ST,CHI015,2020-12-01,19,1154377.984,1857351.591,41.764391,-87.709728,"(41.76439095689881, -87.70972841983624)"
369,W ROOSEVELT,2917 W ROOSEVELT,CHI019,2020-07-28,36,1156991.618,1894531.138,41.866364,-87.699143,"(41.866364024167034, -87.69914296647906)"
370,E 95TH ST,3542 E 95TH ST,CHI141,2020-07-28,8,1201629.280,1842674.179,41.723045,-87.537041,"(41.72304461975978, -87.5370407583455)"
371,S ASHLAND AVE,8345 S ASHLAND AVE,CHI168,2019-07-27,27,1167170.494,1849194.117,41.741742,-87.663073,"(41.741741651401504, -87.66307332925098)"
...,...,...,...,...,...,...,...,...,...,...
308277,W FOREST PRESERVE AV,8020 W FOREST PRESERVE AV,CHI174,2022-06-04,212,1121895.053,1922705.872,41.944319,-87.827378,"(41.944318833069445, -87.8273782786742)"
308278,N NARRAGANSETT AVE,3116 N NARRAGANSETT AVE,CHI132,2022-06-03,5,1133159.075,1920109.559,41.937004,-87.786037,"(41.93700435024341, -87.78603672187927)"
308279,W BELMONT AVE,3810 W BELMONT AVE,CHI089,2022-06-02,11,1150363.864,1921047.101,41.939258,-87.722781,"(41.93925823071868, -87.72278142793657)"
308280,N COLUMBUS DR,450 N COLUMBUS DR,CHI125,2022-06-04,15,1178351.216,1903356.802,41.890122,-87.620461,"(41.890122352505166, -87.62046139513696)"
308281,W ADDISON ST,8006 W ADDISON ST,CHI176,2022-06-04,28,1122009.360,1923001.912,41.945129,-87.826952,"(41.945129353961654, -87.8269516993975)"

In [6]:
# run value_counts() on years
df['VIOLATION DATE'].dt.year.value_counts()

2019    39109
2021    38125
2018    37799
2016    37532
2017    36877
2015    36392
2020    28290
2022    26093
2014    16318
Name: VIOLATION DATE, dtype: int64

In [7]:
# remove data from 2014
filtered_df = df.loc[df['VIOLATION DATE'] > '2014-12-31']
filtered_df

,STREET,ADDRESS,CAMERA ID,VIOLATION DATE,VIOLATIONS,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION
366,W AUGUSTA,3100 W AUGUSTA,CHI011,2020-12-01,23,1155438.363,1906531.351,41.899325,-87.704522,"(41.89932514072566, -87.70452234551168)"
368,W 71ST,3450 W 71ST,CHI015,2020-12-01,19,1154377.984,1857351.591,41.764391,-87.709728,"(41.76439095689881, -87.70972841983624)"
369,W ROOSEVELT,2917 W ROOSEVELT,CHI019,2020-07-28,36,1156991.618,1894531.138,41.866364,-87.699143,"(41.866364024167034, -87.69914296647906)"
370,E 95TH ST,3542 E 95TH ST,CHI141,2020-07-28,8,1201629.280,1842674.179,41.723045,-87.537041,"(41.72304461975978, -87.5370407583455)"
371,S ASHLAND AVE,8345 S ASHLAND AVE,CHI168,2019-07-27,27,1167170.494,1849194.117,41.741742,-87.663073,"(41.741741651401504, -87.66307332925098)"
...,...,...,...,...,...,...,...,...,...,...
308277,W FOREST PRESERVE AV,8020 W FOREST PRESERVE AV,CHI174,2022-06-04,212,1121895.053,1922705.872,41.944319,-87.827378,"(41.944318833069445, -87.8273782786742)"
308278,N NARRAGANSETT AVE,3116 N NARRAGANSETT AVE,CHI132,2022-06-03,5,1133159.075,1920109.559,41.937004,-87.786037,"(41.93700435024341, -87.78603672187927)"
308279,W BELMONT AVE,3810 W BELMONT AVE,CHI089,2022-06-02,11,1150363.864,1921047.101,41.939258,-87.722781,"(41.93925823071868, -87.72278142793657)"
308280,N COLUMBUS DR,450 N COLUMBUS DR,CHI125,2022-06-04,15,1178351.216,1903356.802,41.890122,-87.620461,"(41.890122352505166, -87.62046139513696)"
308281,W ADDISON ST,8006 W ADDISON ST,CHI176,2022-06-04,28,1122009.360,1923001.912,41.945129,-87.826952,"(41.945129353961654, -87.8269516993975)"

In [8]:
daily_violations = filtered_df.sort_values('VIOLATIONS', ascending=False)
daily_violations

,STREET,ADDRESS,CAMERA ID,VIOLATION DATE,VIOLATIONS,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION
252001,W IRVING PARK,2705 W IRVING PARK,CHI079,2022-03-12,827,1157555.243,1926426.211,41.953875,-87.696204,"(41.95387526461699, -87.69620408862693)"
245025,W IRVING PARK,2705 W IRVING PARK,CHI079,2022-03-05,773,1157555.243,1926426.211,41.953875,-87.696204,"(41.95387526461699, -87.69620408862693)"
261980,E MORGAN DR,536 E MORGAN DR,CHI029,2021-03-13,771,1180984.657,1868164.766,41.793493,-87.611876,"(41.793492645896656, -87.6118759701359)"
262723,W IRVING PARK,2705 W IRVING PARK,CHI079,2022-03-20,764,1157555.243,1926426.211,41.953875,-87.696204,"(41.95387526461699, -87.69620408862693)"
253422,W IRVING PARK,2705 W IRVING PARK,CHI079,2022-03-13,761,1157555.243,1926426.211,41.953875,-87.696204,"(41.95387526461699, -87.69620408862693)"
...,...,...,...,...,...,...,...,...,...,...
172764,N ASHLAND,2432 N ASHLAND,CHI092,2019-01-24,1,1165215.788,1916401.754,41.926208,-87.668329,"(41.92620790295943, -87.66832897708693)"
122073,W 103RD ST,2416 W 103RD ST,CHI154,2017-11-16,1,1161995.609,1836307.313,41.706487,-87.682391,"(41.70648720051648, -87.68239105927896)"
122063,N WESTERN AVE,1226 N WESTERN AVE,CHI128,2017-09-28,1,1160143.276,1908203.274,41.903817,-87.687195,"(41.90381710275111, -87.6871949977686)"
122062,95TH,57 E 95TH,CHI035,2018-06-10,1,1178586.982,1841966.714,41.721657,-87.621463,"(41.72165713317433, -87.62146289865515)"
139064,N NARRAGANSETT AVE,3115 N NARRAGANSETT AVE,CHI104,2016-01-14,1,1133239.690,1920090.575,41.936951,-87.785741,"(41.93695084197675, -87.78574089058974)"

In [9]:
total_violations = filtered_df['VIOLATIONS'].sum()
total_violations

10328241

In [10]:
address_list = []

for i in range(len(filtered_df)):
    address = filtered_df.iloc[i,1]
    if address not in address_list:
        address_list.append(address)

len(address_list)

160

In [12]:
# create a dataframe that lists each unique address, the total number of violations at that address in the entire dataset, and the lat and lng location of the address
grouped_df = filtered_df.groupby(['ADDRESS'], as_index=False, sort=False).agg({'VIOLATIONS':'sum', 'LATITUDE':'first', 'LONGITUDE':'first'})
sorted_and_grouped = grouped_df.sort_values('VIOLATIONS', ascending=False)
sorted_and_grouped.head(20)

                       ADDRESS  VIOLATIONS   LATITUDE  LONGITUDE
16           4909 N CICERO AVE      494031  41.970135 -87.747724
24                 445 W 127TH      466859  41.663174 -87.633520
31             536 E MORGAN DR      361251  41.793493 -87.611876
37           4124 W FOSTER AVE      347947  41.975605 -87.731670
157       10318 S INDIANAPOLIS      337416  41.707577 -87.529848
50                2900 W OGDEN      315989  41.860408 -87.698672
13         4831 W LAWRENCE AVE      276069  41.967902 -87.749079
7           1142 W IRVING PARK      262520  41.954541 -87.658573
55          2705 W IRVING PARK      251488  41.953875 -87.696204
35              3843 S WESTERN      223517  41.823564 -87.684721
48           3200 S ARCHER AVE      196507  41.835958 -87.668790
26              5816 W JACKSON      194284  41.877189 -87.770370
11   8020 W FOREST PRESERVE AV      193472  41.944319 -87.827378
90                 115 N OGDEN      172839  41.883192 -87.664115
76               6909 S KEDZIE      159607  41.767732 -87.702738
5         1315 W GARFIELD BLVD      149854  41.793645 -87.657861
25             3137 W PETERSON      148603  41.990282 -87.708245
95        5330 S COTTAGE GROVE      146226  41.797704 -87.606445
58       6226 W IRVING PARK RD      145444  41.953075 -87.782826
18              6523 N WESTERN      144943  42.000260 -87.689803

In [13]:
# export sorted_and_grouped dataframe to json file
json = sorted_and_grouped.to_json('./speed_export.json', orient='index')